build:  
    environment:
        php:
            version: 5.5.12
    tests:
        override:
            - 
                command:  cd tests && phpunit --coverage-clover=coverage unit
                coverage:
                    file: coverage
                    format: php-clover
