build:  
    environment:
        php:
            version: 5.5.12
    tests:
        override:
            - 
                command:  phpunit --coverage-clover=coverage
                    file: coverage
                    format: php-clover
