language: php
php:
    - 5.5
    - 5.6
    - 7
install:
    - composer install
script:
    make test
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
