INSERT INTO `exam`.`Exam`(`name`,`slug`,`description`)VALUES("ZCE", "zce", "Exam about php zend certified engineer");
INSERT INTO `exam`.`Exam`(`name`,`slug`,`description`)VALUES("LP1" , "lp1", "Exam about linux centification level one");
INSERT INTO `exam`.`Exam`(`name`,`slug`,`description`)VALUES("LP2" , "lp2", "Exam about linux centification level two");
INSERT INTO `exam`.`Exam`(`name`,`slug`,`description`)VALUES("Mysql db admin", "mysql-db-admin", "Exam about mysql");
INSERT INTO `exam`.`Exam`(`name`,`slug`,`description`)VALUES("Java", "java", "Exam about Java");
INSERT INTO `exam`.`Question`(`exam_id`,`title`, `slug`) VALUES (1, "Which function return all methods of an object?", "which-function-return-all-methods-of-an-object") ;
INSERT INTO `exam`.`Question`(`exam_id`,`title`, `slug`) VALUES (1, "Which these words are not reserveds in php 5.5?", "which-these-words-are-not-reserveds-in-php55");
insert into `Choice` (`question_id`, `title`) values (1, 'get_methods');
insert into `Choice` (`question_id`, `title`) values (1, 'get_class');
insert into `Choice` (`question_id`, `title`) values (1, 'get_operators');
insert into `Choice` (`question_id`, `title`) values (1, 'get_func_names');
